parameters:
    kernel.storage_dir: '%kernel.project_dir%/var'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Classic\Secret\CliClient\Command\:
        resource: '../src/Command'
#        tags: ['console.command']

    Classic\Secret\CliClient\Service\Storage:
        lazy: true
        arguments:
            $path: '%kernel.storage_dir%/storage.json'

    Classic\Secret\CliClient\Client\Client:
        arguments:
            $coreUrl: '%env(CORE_URI)%'

    Classic\Secret\Package\Crypt\Operator\CryptoFactory: ~

    Classic\Secret\CliClient\Service\RequestSignatureService: ~